name: CI
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Setup workspace
        run: dotnet tool restore
      - name: Build package
        run: dotnet build src
